### ISSUE TITLE
Actviate Tab on Hover - Please make it working in tab stacks

### ISSUE THREAD

**Issue by N3C2L** [luetage/vivaldi_modding#6] opened 2021-03-14 11:13 UTC
Hello,

Can you update the script to work in tab stacks? 
Much appreciated. 
Regards

**Comment by luetage** [comment] 2021-03-14 11:31
Which script? You are raising an issue for the whole project, I cannot know which mod you are referring to.

**Comment by N3C2L** [comment] 2021-03-14 11:54
Sorry. It is about the activate tab on hover script. I reopened the issue and changed title.

**Comment by luetage** [comment] 2021-03-14 13:59
So I took a look at it. The mod works by updating the hovered tab and making it active by checking its id and invoking chrome.tabs api. The problem is chrome.tabs requires the id to be a number and the parent tab of stacked tabs doesn’t have a number but a string with mixed letters and numbers, which chrome.tabs doesn’t accept. Why Vivaldi did this I don’t know, it’s definitely not standard, but I currently see no easy way to solve the issue.

**Comment by N3C2L** [comment] 2021-03-14 14:56
Thanks for looking into it. Maybe you have an idea someday for solving it.

**Comment by luetage** [comment] 2021-03-14 21:13
I implemented an ugly solution, but it’s necessary, the click for the parent stack is being simulated now. Seems to work, tell me whether you have issues with this. Gonna close this now.

**Closed as completed by luetage** 2021-03-14 21:13 UTC
